handlers = java.util.logging.ConsoleHandler
.level = WARNING
com.arcadedb.level = WARNING
io.undertow.level = WARNING
org.xnio.level = WARNING
org.jboss.level = WARNING
java.util.logging.ConsoleHandler.level = WARNING
